[workspace.package]
version = "0.1.0"
edition = "2024"
categories = [ "rendering", "gui" ]
repository = "https://github.com/csmoe/dawn-rs"
license = "BSD-3-Clause"

[workspace]
members = [
    "codegen"
]

[workspace.dependencies]

[package]
name = "dawn-rs"
edition.workspace = true
description = "Rust bindings for google/dawn"
license.workspace = true
categories.workspace = true

[dependencies]
