[package]
name = "dawn-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["codegen"]

[dependencies]
bitflags = "2"

[build-dependencies]
dawn-codegen = { path = "codegen" }

[dev-dependencies]
winit = "0.28"
objc2 = "0.5"

[features]
default = ["dawn", "native"]
dawn = []
native = []
emscripten = []
compat = []

[[example]]
name = "adapter-info"
path = "examples/adapter_info.rs"
