[workspace.package]
version = "0.1.0"
edition = "2024"
categories = [ "rendering", "gui" ]
repository = "https://github.com/csmoe/dawn-rs"
license = "BSD-3-Clause"

[workspace]
members = [
    "codegen"
, "examples/dawn-capi"]

[workspace.dependencies]


[package]
name = "dawn-rs"
edition.workspace = true
description = "Rust bindings for google/dawn"
license.workspace = true
categories.workspace = true
build = "build.rs"

[features]
default = []
dawn = []
emscripten = []
native = []
compat = []
art = []
dawn_wire = []

[dependencies]

[build-dependencies]
dawn-codegen = { path = "codegen" }
build-rs = "0.3"

[dev-dependencies]
winit = "0.30.12"
