[package]
name = "dawn-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
heck = "0.4"
prettyplease = "0.2"
syn = { version = "2", default-features = false, features = ["full", "parsing"] }
bindgen = "0.72"
