[package]
name = "dawn-codegen"
version.workspace = true
edition.workspace = true
categories.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
serde_json = { version = "1" }
serde = { version = "1", features = ["derive"] }
