[package]
name = "dawn-capi"
version.workspace = true
edition.workspace = true
categories.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
winit = "0.30.12"
dawn-rs = { path = "../.." }
